### ISSUE TITLE
태그검색시 검색되는 태그 엔터를 통해 바로 입력되도록

### ISSUE THREAD

**Issue by Ruzi** [skullacy/mydearnest-web#33]
예압

**Comment by skullacy** [comment]
반응속도 향상을 목표로 잡겠음.

현재의 알고리즘상 검색어를 입력하면 서버에 해당 태그를 요청 후 알맞는 태그만 가져오는 방식을
사용중인데, 우리가 입력하는 태그는 그 종류가 한정되어있어 해당 알고리즘은 서버의 부하만 증가시킨다.

Sol.
1. 처음 페이지 로딩시 모든 태그리스트를 한번에 가져옴.
2. Autocomplete의 dataSource를 스크립트 객체로 저장시켜 이용한다.
3. 위와 같은 방식을 사용하면 서버의 요청횟수가 기하급수적으로 내려가므로 0초 Latency가능.

**Comment by skullacy** [comment]
추가. 

검색 후 엔터를 치면 조건에 맞는 검색결과가 두개 이상일 경우 Select Section으로 이동.
결과가 한개일 경우 바로 반영되게 하기.

**Comment by skullacy** [comment]
구현 시작
